services:
  - type: web
    name: rag-knowledge-assistant-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    plan: free
